name: Manual Logging

on:
  workflow_dispatch:
    inputs:
      entorno:
        description: 'Entorno de ejecución'
        required: true
        default: 'produccion'

permissions:
  contents: read
  # Añade aquí otros permisos si los necesitas

jobs:
  registrar_las_entradas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
      
      - name: Ejemplo de paso
        run: echo "Registrando entrada en el entorno ${{ github.event.inputs.entorno }}"
        
