name: Manual Logging
on: workflow_dispatch

jobs:
  log-entries:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Log message
        run: echo "Registrando entrada..."
        
