name: Manual Logging

on:
  workflow_dispatch:
    inputs:
      entorno:
        description: 'Entorno de ejecución'
        required: true
        default: 'production'

permissions: {}

jobs:
  registrar-las-entradas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Log message
        run: echo "Registrando entrada en el entorno ${{ github.event.inputs.entorno }}"
        
